### Keycloak — récupération de tokens (realm: demo2)
### Base : http://localhost:8080  |  Token endpoint OIDC

@host = http://localhost:8080
@realm = demo2
@tokenUrl = {{host}}/realms/{{realm}}/protocol/openid-connect/token

###############################################################
# 1) MACHINE TO MACHINE  —  Client Credentials (api-service)
#    -> access_token uniquement (aucun utilisateur, donc pas d'id_token)
###############################################################
# @name m2m
POST {{tokenUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=api-service
&client_secret=api-service-secret-change-me

###############################################################
# 2) UTILISATEUR  —  Resource Owner Password Credentials (login + mot de passe)
#    -> access_token + id_token (scope openid requis pour l'id_token)
#    PRE-REQUIS : "directAccessGrantsEnabled": true sur le client web-app
###############################################################
# @name userLogin
POST {{tokenUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=web-app
&client_secret=web-app-secret-change-me
&username=alice
&password=admin
&scope=openid profile email

###############################################################
# 3) RAFRAÎCHIR le token (utilise le refresh_token de la requête #2)
###############################################################
POST {{tokenUrl}}
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id=web-app
&client_secret=web-app-secret-change-me
&refresh_token=eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2ZjhmNjViYS1mMjIzLTRlOGUtOWI1Mi1hODQ4YTMwYjU3Y2MifQ.eyJleHAiOjE3ODA5Nzk1NDMsImlhdCI6MTc4MDk3Nzc0MywianRpIjoiN2VkZWNjODUtMmEyOS04ODkxLWE4M2MtYzZkMTBkNWIyNzNhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvZGVtbzIiLCJzdWIiOiJiYzgyZjVjNS01ZTc4LTQ1NGYtOTQ4Zi00M2E3ODg0ODFiZmYiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoid2ViLWFwcCIsInNpZCI6IkVJbWFUc2F5VnNSMFlYeGJ3d180a3NiUyIsInNjb3BlIjoib3BlbmlkIHdlYi1vcmlnaW5zIHJvbGVzIHByb2ZpbGUgYmFzaWMgYWNyIGVtYWlsIn0.aUTVDTuRLco7dD5ZaU9XDFrEaWcXC_YJwtJuFjaJMo2i-OaQ1zIqDXKlOBUwzjX5Qo0XK9gvs0Lg52hXo1xuGg


###############################################################
# 4) Vérifier un token  —  Introspection (api-service)
###############################################################
POST {{host}}/realms/{{realm}}/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded

client_id=api-service
&client_secret=api-service-secret-change-me
&token={{userLogin.response.body.access_token}}

###############################################################
# 5) UserInfo  —  avec le access_token utilisateur
###############################################################
GET {{host}}/realms/{{realm}}/protocol/openid-connect/userinfo
Authorization: Bearer {{userLogin.response.body.access_token}}